### ISSUE TITLE
Bikeshed: next/complete/error vs. other names

### ISSUE THREAD

**Issue by domenic** [domfarolino/observable#7]
I suspect this has been discussed in the literature before, so I apologize for re-raising it. But it would be worthwhile to document it somewhere in the explainer.

Basically, are next/complete/error the best names? Ones that immediately come to mind from a JS language design perspective are [next/return/throw](https://tc39.es/ecma262/#sec-iterator-interface). There's also [an argument to be made](https://tc39.es/ecma262/#sec-iterator-interface) for yield/return/throw.

One related idea to keep in mind is how promises chose resolve|fullfill / reject, instead of return / throw. There are a few reasons for this:

- The subtle differences between resolve and fulfill meant neither was a great map onto "return".
- Back in the days of ES3 when Promises/A+ was first being created, you couldn't use keywords like throw/return as property names, so instead of `Promise["throw"]()` we did `Promise.reject()`.
  - Even today, it'd be annoying to have to do `new Promise((rreturn, tthrow) => { ... })` to avoid the still-existing prohibition on using keywords as variable names.
- Keeping the namespaces distinct helps give us a short vocabulary to talk about "async throwing" and "async returning", with the single words "rejecting" and "resolving".

I'm not sure any of those arguments are super-compelling, but maybe they set a historical precedent.

**Comment by benlesh** [comment]
> How strong is community precedent?

Honestly stronger than I thought (and you know I'm bullish on this)... I added only the most prominent examples here: https://github.com/domfarolino/observable/issues/7

But if you do a GitHub search for JavaScript or TypeScript code that references `Symbol.observable`, or `@@observable`, or `symbol-observable`, it bubbles up a lot of code that is using as same-shaped observable.

**Comment by domfarolino** [comment]
The only prior discussion related to renaming these that I could find in the TC39 repo was https://github.com/tc39/proposal-observable/issues/185, which was more than just a simple rename, but rather an attempt to coalesce "error" and "complete" into a single method.

Otherwise, I don't see much discussion about this in the past, and people seem to like the current names established by community precedent so I think I'll close. We can revisit this if there is a stronger community-driven motivation to rename these perhaps.
